### ISSUE TITLE
Encountered an exception while running action 'buy_form'. Bot will continue, but the actions events are lost.

### ISSUE THREAD

**Issue by Maadhav** [cedextech/rasa-chatbot-templates#2]
Encountered an exception while running action 'buy_form'. Bot will continue, but the actions events are lost. Please check the logs of your action server for more information.

**Comment by freakeinstein** [comment]
Hi @Maadhav are you running action server in a new terminal? If not please open a new terminal in the same directory and run the command `rasa run actions`. 

If you already are running actions server, can you share the terminal error logs here?

**Comment by aminaanvar** [comment]
Hi while running rasa run actions and rasa x, i am able to get into the program, but whille clicking on 'bookrooms' it doesnt gives the output rather than showing a part of program code? why is that so? please respond
