### ISSUE TITLE
How to run these template on RASA X?

### ISSUE THREAD

**Issue by stefanbadi** [cedextech/rasa-chatbot-templates#5]
How can I run these templates on RASA X?

**Comment by sids07** [comment]
> How can I run these templates on RASA X?

Yes I too am only getting like text written of this custom json templates.

**Comment by pudasainishushant** [comment]
@stefanbadi  and @sids07 First train the model with rasa train and open rasa x from the project directory. That should do it.

**Comment by sids07** [comment]
@pudasainishushant bro i have trained and tried to acess using shell as well as rasa x but i am getting the written custom json payload function as output not images and subtitles with buttons.

**Comment by anand0009** [comment]
> > How can I run these templates on RASA X?
> 
> Yes I too am only getting like text written of this custom json templates.

hey sid....if u have solved the problem...please let me know....please its urgent

**Comment by shreeraj04** [comment]
@sids07 @anand0009 Please post your queries with snapshot so that it will be easy to understand quickly.
